### ISSUE TITLE
Uncaught ReferenceError: arrDay is not defined

### ISSUE THREAD

**Issue by watership** [jinghaoo/mobile-selector#1]
![wx20170418-174403](https://cloud.githubusercontent.com/assets/2470422/25124617/d5842312-245e-11e7-9223-c68097a21e45.png)

引用时候报错

**Comment by jinghaoo** [comment]
@watership 感谢您对本插件的支持，通过我的排查暂无发现产生此bug的缘由，能具体描述下您的项目吗？
